# Generated by Django 4.0.5 on 2023-08-21 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_trainer', models.CharField(max_length=40)),
                ('course_timings', models.TimeField()),
                ('course_fees', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.IntegerField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mobile_Number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=70)),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
    ]
